/**
 * Lucide-compatible names backed by PatternFly / Font Awesome icons.
 * Use: import { X, Search } from "@/lib/pfIcons";
 */
import * as React from "react";
import { Spinner } from "@patternfly/react-core";
import AngleDownIcon from "@patternfly/react-icons/dist/esm/icons/angle-down-icon";
import AngleRightIcon from "@patternfly/react-icons/dist/esm/icons/angle-right-icon";
import AngleUpIcon from "@patternfly/react-icons/dist/esm/icons/angle-up-icon";
import ArrowsAltHIcon from "@patternfly/react-icons/dist/esm/icons/arrows-alt-h-icon";
import ArrowLeftIcon from "@patternfly/react-icons/dist/esm/icons/arrow-left-icon";
import ArrowRightIcon from "@patternfly/react-icons/dist/esm/icons/arrow-right-icon";
import BellIcon from "@patternfly/react-icons/dist/esm/icons/bell-icon";
import BoltIcon from "@patternfly/react-icons/dist/esm/icons/bolt-icon";
import BookmarkIcon from "@patternfly/react-icons/dist/esm/icons/bookmark-icon";
import BoxIcon from "@patternfly/react-icons/dist/esm/icons/box-icon";
import BugIcon from "@patternfly/react-icons/dist/esm/icons/bug-icon";
import CalendarAltIcon from "@patternfly/react-icons/dist/esm/icons/calendar-alt-icon";
import CheckCircleIcon from "@patternfly/react-icons/dist/esm/icons/check-circle-icon";
import CheckIcon from "@patternfly/react-icons/dist/esm/icons/check-icon";
import ClockIcon from "@patternfly/react-icons/dist/esm/icons/clock-icon";
import CodeBranchIcon from "@patternfly/react-icons/dist/esm/icons/code-branch-icon";
import CodeIcon from "@patternfly/react-icons/dist/esm/icons/code-icon";
import ColumnsIcon from "@patternfly/react-icons/dist/esm/icons/columns-icon";
import CopyIcon from "@patternfly/react-icons/dist/esm/icons/copy-icon";
import CubeIcon from "@patternfly/react-icons/dist/esm/icons/cube-icon";
import DatabaseIcon from "@patternfly/react-icons/dist/esm/icons/database-icon";
import DownloadIcon from "@patternfly/react-icons/dist/esm/icons/download-icon";
import EditIcon from "@patternfly/react-icons/dist/esm/icons/edit-icon";
import EllipsisVIcon from "@patternfly/react-icons/dist/esm/icons/ellipsis-v-icon";
import ExclamationCircleIcon from "@patternfly/react-icons/dist/esm/icons/exclamation-circle-icon";
import ExclamationTriangleIcon from "@patternfly/react-icons/dist/esm/icons/exclamation-triangle-icon";
import ExpandArrowsAltIcon from "@patternfly/react-icons/dist/esm/icons/expand-arrows-alt-icon";
import ExternalLinkAltIcon from "@patternfly/react-icons/dist/esm/icons/external-link-alt-icon";
import EyeIcon from "@patternfly/react-icons/dist/esm/icons/eye-icon";
import FileAltIcon from "@patternfly/react-icons/dist/esm/icons/file-alt-icon";
import FilterIcon from "@patternfly/react-icons/dist/esm/icons/filter-icon";
import FolderIcon from "@patternfly/react-icons/dist/esm/icons/folder-icon";
import GlobeIcon from "@patternfly/react-icons/dist/esm/icons/globe-icon";
import HddIcon from "@patternfly/react-icons/dist/esm/icons/hdd-icon";
import HeartbeatIcon from "@patternfly/react-icons/dist/esm/icons/heartbeat-icon";
import InfoCircleIcon from "@patternfly/react-icons/dist/esm/icons/info-circle-icon";
import LayerGroupIcon from "@patternfly/react-icons/dist/esm/icons/layer-group-icon";
import ListIcon from "@patternfly/react-icons/dist/esm/icons/list-icon";
import LocationArrowIcon from "@patternfly/react-icons/dist/esm/icons/location-arrow-icon";
import LockIcon from "@patternfly/react-icons/dist/esm/icons/lock-icon";
import LongArrowAltUpIcon from "@patternfly/react-icons/dist/esm/icons/long-arrow-alt-up-icon";
import MicrochipIcon from "@patternfly/react-icons/dist/esm/icons/microchip-icon";
import NetworkWiredIcon from "@patternfly/react-icons/dist/esm/icons/network-wired-icon";
import PaperclipIcon from "@patternfly/react-icons/dist/esm/icons/paperclip-icon";
import PaperPlaneIcon from "@patternfly/react-icons/dist/esm/icons/paper-plane-icon";
import PauseIcon from "@patternfly/react-icons/dist/esm/icons/pause-icon";
import PencilAltIcon from "@patternfly/react-icons/dist/esm/icons/pencil-alt-icon";
import PlayCircleIcon from "@patternfly/react-icons/dist/esm/icons/play-circle-icon";
import PlayIcon from "@patternfly/react-icons/dist/esm/icons/play-icon";
import PlusIcon from "@patternfly/react-icons/dist/esm/icons/plus-icon";
import QuestionCircleIcon from "@patternfly/react-icons/dist/esm/icons/question-circle-icon";
import RobotIcon from "@patternfly/react-icons/dist/esm/icons/robot-icon";
import { RhAiExperienceIcon } from "@/components/icons/RhAiExperienceIcon";
import SearchIcon from "@patternfly/react-icons/dist/esm/icons/search-icon";
import SearchMinusIcon from "@patternfly/react-icons/dist/esm/icons/search-minus-icon";
import SearchPlusIcon from "@patternfly/react-icons/dist/esm/icons/search-plus-icon";
import ServerIcon from "@patternfly/react-icons/dist/esm/icons/server-icon";
import ShieldAltIcon from "@patternfly/react-icons/dist/esm/icons/shield-alt-icon";
import StarIcon from "@patternfly/react-icons/dist/esm/icons/star-icon";
import SyncAltIcon from "@patternfly/react-icons/dist/esm/icons/sync-alt-icon";
import TasksIcon from "@patternfly/react-icons/dist/esm/icons/tasks-icon";
import TerminalIcon from "@patternfly/react-icons/dist/esm/icons/terminal-icon";
import ThIcon from "@patternfly/react-icons/dist/esm/icons/th-icon";
import ThumbsDownIcon from "@patternfly/react-icons/dist/esm/icons/thumbs-down-icon";
import ThumbsUpIcon from "@patternfly/react-icons/dist/esm/icons/thumbs-up-icon";
import TimesCircleIcon from "@patternfly/react-icons/dist/esm/icons/times-circle-icon";
import TimesIcon from "@patternfly/react-icons/dist/esm/icons/times-icon";
import TintIcon from "@patternfly/react-icons/dist/esm/icons/tint-icon";
import TrashIcon from "@patternfly/react-icons/dist/esm/icons/trash-icon";
import UndoIcon from "@patternfly/react-icons/dist/esm/icons/undo-icon";
import UserCogIcon from "@patternfly/react-icons/dist/esm/icons/user-cog-icon";
import UserIcon from "@patternfly/react-icons/dist/esm/icons/user-icon";
import UsersIcon from "@patternfly/react-icons/dist/esm/icons/users-icon";
import VolumeUpIcon from "@patternfly/react-icons/dist/esm/icons/volume-up-icon";
import CogIcon from "@patternfly/react-icons/dist/esm/icons/cog-icon";

export function Loader2({
  className,
  "aria-label": ariaLabel = "Loading",
  ...rest
}: React.ComponentProps<typeof Spinner>) {
  return <Spinner className={className} aria-label={ariaLabel} {...rest} />;
}

export const X = TimesIcon;
export const Search = SearchIcon;
export const RefreshCw = SyncAltIcon;
export const RotateCw = SyncAltIcon;
export const MoreVertical = EllipsisVIcon;
export const CheckCircle = CheckCircleIcon;
export const CheckCircle2 = CheckCircleIcon;
export const Clock = ClockIcon;
export const XCircle = TimesCircleIcon;
export const AlertCircle = ExclamationCircleIcon;
export const PlayCircle = PlayCircleIcon;
export const Filter = FilterIcon;
export const Package = CubeIcon;
export const ArrowLeft = ArrowLeftIcon;
export const ArrowRight = ArrowRightIcon;
export const AlertTriangle = ExclamationTriangleIcon;
export const TriangleAlert = ExclamationTriangleIcon;
export const Check = CheckIcon;
export const Info = InfoCircleIcon;
export const ChevronRight = AngleRightIcon;
export const ChevronDown = AngleDownIcon;
export const ChevronUp = AngleUpIcon;
export const ExternalLink = ExternalLinkAltIcon;
/** RH UI ai-experience sparkle pair — use for AI generated / AI-assisted UI (not the legacy magic wand). */
export const Sparkles = RhAiExperienceIcon;
export const AiExperienceIcon = RhAiExperienceIcon;
export const Eye = EyeIcon;
export const Trash2 = TrashIcon;
export const Send = PaperPlaneIcon;
export const ThumbsUp = ThumbsUpIcon;
export const ThumbsDown = ThumbsDownIcon;
export const Copy = CopyIcon;
export const Bookmark = BookmarkIcon;
export const Volume2 = VolumeUpIcon;
export const Paperclip = PaperclipIcon;
export const Activity = HeartbeatIcon;
export const TrendingUp = LongArrowAltUpIcon;
export const Cpu = MicrochipIcon;
export const HardDrive = HddIcon;
export const Network = NetworkWiredIcon;
export const Star = StarIcon;
export const Droplet = TintIcon;
export const Download = DownloadIcon;
export const Code2 = CodeIcon;
export const Columns2 = ColumnsIcon;
export const FileText = FileAltIcon;
export const Users = UsersIcon;
export const UserCog = UserCogIcon;
export const ListChecks = TasksIcon;
export const Play = PlayIcon;
export const Pause = PauseIcon;
export const Calendar = CalendarAltIcon;
export const Bell = BellIcon;
export const User = UserIcon;
export const RotateCcw = UndoIcon;
export const HelpCircle = QuestionCircleIcon;
export const Shield = ShieldAltIcon;
export const Bot = RobotIcon;
export const Settings = CogIcon;
export const Zap = BoltIcon;
export const Database = DatabaseIcon;
export const Folder = FolderIcon;
export const Layers = LayerGroupIcon;
export const Plus = PlusIcon;
export const Globe = GlobeIcon;
export const Lock = LockIcon;
export const ArrowUpRight = LocationArrowIcon;
export const Edit = EditIcon;
export const Edit2 = PencilAltIcon;
export const Terminal = TerminalIcon;
export const ArrowLeftRight = ArrowsAltHIcon;
export const ZoomIn = SearchPlusIcon;
export const ZoomOut = SearchMinusIcon;
export const Maximize2 = ExpandArrowsAltIcon;
export const List = ListIcon;
export const LayoutGrid = ThIcon;
export const Box = BoxIcon;
export const GitBranch = CodeBranchIcon;
export const Server = ServerIcon;
export const Bug = BugIcon;
